
DROP TABLE IF EXISTS participation_requests CASCADE;
CREATE TABLE participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    requester_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(20) NOT NULL,
    created      TIMESTAMP   NOT NULL
);